### ISSUE TITLE
新看板娘 Tia の改造记事 | Sun

### ISSUE THREAD

**Issue by sunwx17** [sunwx17/BlogComment#13]
https://sunwx17.github.io/posts/6/ 

 最近 Pio 大有泛滥之势，惨象已使我目不忍视了，或许这其中与我有些干系 ，毕竟当初偷师后流出了一大批模型，但我还有什么话可说呢，好吧已无它法，来加个美美哒新老婆 Tia 吧。

**Comment by shy2000** [comment]
找到了一些有趣的东西，话说评论区一直connect error什么鬼，嘛，我会努力的
